### ISSUE TITLE
Faster dataloader init by saving preprocessed

### ISSUE THREAD

**Issue by srikanthmalla** [abduallahmohamed/Social-STGCNN#11]
Hi @abduallahmohamed ,
Do you think saving the preprocessed data will be better instead of running the pre-processing everytime (which takes so much time to process).

    import pickle as pkl

    ...
 
    class TrajectoryDataset(Dataset):

    def __init__(..):

        ....

        self.outfile = self.data_dir+"/processed.pkl"

        if not os.path.exists(self.outfile):

            ....

            # save the preprocessed variables

            out_data = {"seq_start_end": self.seq_start_end, "obs_traj": self.obs_traj, "obs_traj_rel": self.obs_traj_rel, "non_linear_ped": self.non_linear_ped, "v_obs": self.v_obs, "v_pred": self.v_pred, "num_seq": self.num_seq}

            pkl.dump(out_data, open(self.outfile,'wb'))

        else:

            data = pkl.load(open(self.outfile, 'rb'))

            self.seq_start_end = data["seq_start_end"]

            self.obs_traj = data["obs_traj"]

            self.obs_traj_rel = data["obs_traj_rel"]

            self.non_linear_ped = data["non_linear_ped"]

            self.v_obs = data["v_obs"]

            self.v_pred = data["v_pred"]

            self.num_seq = data["num_seq"]

**Comment by abduallahmohamed** [comment]
Definitely it will speed up. We didn't include such approach in the code as we were testing different kernels. Please feel free to fork it, modify, test and send a pull request.
