### ISSUE TITLE
Test Accuracy varies

### ISSUE THREAD

**Issue by XHwind** [abduallahmohamed/Social-STGCNN#16]
Thanks for sharing the code! It would be great if you could provide the random seed you used for the testing process. Since the sampling produces different samples, running test.py each time can get different results. And currently, I could not reach the results you reported in the paper.

**Comment by abduallahmohamed** [comment]
Hi, 
I don't have the random seed setting unfortunately for the testing process. 
The results on the paper: 
![image](https://user-images.githubusercontent.com/22107547/78068435-04a0f980-735e-11ea-9417-ee7c96db8da9.png)
in which I used the exact weights at this commit https://github.com/abduallahmohamed/Social-STGCNN/commit/08586f5a33286d6c4d9b7d69efc98db7ccd8c24d

The current commit https://github.com/abduallahmohamed/Social-STGCNN/commit/9347d305f6b86dc844d23253e43c5f064dfd9d73 produces the same results but a better code. 

I ran the current commit 5 times and I got this: 
Avg ADE: 0.45454306419527174
Avg FDE: 0.7595214509051573
===
Avg ADE: 0.45379038655395193
Avg FDE: 0.7586752631148943
===
Avg ADE: 0.45534983524405115
Avg FDE: 0.764066836462734
===
Avg ADE: 0.4528705978716407
Avg FDE: 0.758386864610435
===
Avg ADE: 0.45146318510285505
Avg FDE: 0.7567930058603392

Please note in the paper we show such STD and mean for 100% usage of the data: 
![image](https://user-images.githubusercontent.com/22107547/78068758-9872c580-735e-11ea-835a-682a2a834dd5.png)

So, the numbers will vary but they will be around 0.44-45/0.75 based on the run. 

I hope this helps you.
