### ISSUE TITLE
Unit and frame rate of data

### ISSUE THREAD

**Issue by TimSchoonbeek** [abduallahmohamed/Social-STGCNN#17]
Could you specify the unit (feet / meters) and frame rate of the processed data that is present in the datasets folder?

**Comment by abduallahmohamed** [comment]
The unit is in meters, the frames rate is the data is sampled each 0.4 sec. I'm using common datasets for this problem ETH[1] and UCY[2]. 

[1]Stefano Pellegrini, Andreas Ess, Konrad Schindler, and LucVan Gool. You’ll never walk alone: Modeling social behaviorfor multi-target tracking.  In2009 IEEE 12th InternationalConference on Computer Vision, pages 261–268. IEEE, 2009
[2] Alon  Lerner,  Yiorgos  Chrysanthou,  and  Dani  Lischinski.Crowds by example. InComputer graphics forum, volume 26,pages 655–664. Wiley Online Library, 2007.

**Comment by TimSchoonbeek** [comment]
Thank you for your answer. I am asking this because I would like to test performance for sampling at different rates, for instance 0.8 fps. To me it is still unclear where exactly you sample at 0.4 fps, do you do this when pre-processing the data (or is the data already sampled at 0.4 fps) or do you do then when reading the data in the TrajectoryDataset class? If it is the latter, could you refer me to the lines where you do this? I seem to be overlooking this.

**Comment by abduallahmohamed** [comment]
The data itself was released, sampled and annotated like this, I'm just loading it into the dataloader.
So, this is like a bench-mark used in this area. Also, more details the standard bench mark is 8/12 use 8 frames to predict 12 frames into the future. 

I'd be interested to see the performance at different rates too, please feel free to share the results or sub of it here.

**Comment by TimSchoonbeek** [comment]
Thanks you for the info, I will let you know if I get some proper results.
