### ISSUE TITLE
If just one pedestrian in one scene，how to deal in your code?

### ISSUE THREAD

**Issue by buaafish** [abduallahmohamed/Social-STGCNN#19]
I see that your code deals with more than two pedestrians. How to deal with one pedestrian?

**Comment by abduallahmohamed** [comment]
The dataset I'm using only allows for at least two peds, and this is a common settings for this problem as a benchmarking baseline. 

Other than this, if you wanna use it for one peds you can create a virtual ped that doesn't move, yet I didn't try this personally. I do like to see the results of this if you tried it out. 

Thanks for your question

**Comment by xzf87845804** [comment]
@buaafish Hi, have you solved the prediction of only one pedestrian?
