### ISSUE TITLE
normalized adjcency or laplacian matrix ? 

### ISSUE THREAD

**Issue by JoeHEZHAO** [abduallahmohamed/Social-STGCNN#22]
https://github.com/abduallahmohamed/Social-STGCNN/blob/9347d305f6b86dc844d23253e43c5f064dfd9d73/utils.py#L50

Dear Authors

Thanks for your great work !

May I ask: above referred function (nx.normalized_laplacian_matrix) returns the normalized laplacian matrix, which is slightly away from normalized adjacency matrix. Is this your intention ?

For example, when I visualize A_obs from test-loader of eth dataset, array A_obs contains negative values, which is totally correct for normalized_laplacian_matrix. 

Thanks for your time !

**Comment by abduallahmohamed** [comment]
Thanks for asking. 

If you have an adjacency matrix **A**, and a degree node matrix **D** you can normalize it by doing what I call Kipf's normalization which is a form of reduced adjacency matrix [1]: 
![image](https://user-images.githubusercontent.com/22107547/82113934-188e9800-971f-11ea-89ad-eb7f4442f372.png)
But in graph CNN this is slightly different: The **A** becomes 
![image](https://user-images.githubusercontent.com/22107547/82114626-7624e380-9723-11ea-9249-67356a1d5838.png)
Then the normalization becomes: 
![image](https://user-images.githubusercontent.com/22107547/82113976-77541180-971f-11ea-9f2f-0b045d994eb6.png)

I believe what we used here was a Laplacian normalization with accounting to self nodes by adding identity to the nodes  https://github.com/abduallahmohamed/Social-STGCNN/blob/9347d305f6b86dc844d23253e43c5f064dfd9d73/utils.py#L43 . 

I did a quick test to illustrate the difference: 
```python
import networkx as nx
import numpy as np 

#Kipf's normalization

A = np.asarray([[0,5,9],[5,0,8],[9,8,0]])
print("A Matrix")
print(A)
A_hat = A+np.eye(3)
print("A_hat Matrix")
print(Ahat)
D_hat = np.eye(3)*2 +np.eye(3) #Fully connected graph degree matrix of A_hat
print("D_hat Matrix")
print(D)
D_half_inv = np.linalg.inv(np.sqrt(D)) 
Kip_normalization = np.matmul(np.matmul(D_half_inv,A_hat),D_half_inv)
print("\n Kipf normalization")
print(Kip_normalization)

#Using laplacian 
G = nx.from_numpy_matrix(A_hat) #create a graph 
A_lapl = nx.normalized_laplacian_matrix(G).toarray()
print("\n Laplacian normalization")
print(A_lapl)
```
which yields: 
```
A Matrix
[[0 5 9]
 [5 0 8]
 [9 8 0]]
A_hat Matrix
[[1. 5. 9.]
 [5. 1. 8.]
 [9. 8. 1.]]
D_hat Matrix
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]

 Kipf normalization
[[0.33333333 1.66666667 3.        ]
 [1.66666667 0.33333333 2.66666667]
 [3.         2.66666667 0.33333333]]

 Laplacian normalization
[[ 0.93333333 -0.34503278 -0.54772256]
 [-0.34503278  0.92857143 -0.50395263]
 [-0.54772256 -0.50395263  0.94444444]]
```
Thanks for noticing this, I will check into more details and either update the paper or the code to see which works best, according to [2] I think the proposed normalization by Kipf is to avoid the computation of lapalcian.


[1] https://en.wikipedia.org/wiki/Laplacian_matrix
[2] https://tkipf.github.io/graph-convolutional-networks/

**Comment by JoeHEZHAO** [comment]
Dear Authors

Thanks for your detailed reply ! The example you provided is exactly what I have observed. 

Just wondering: could your way be another approach to do approximation in [2] ? 

#1. Original paper assumes learning will adapt theta = theta_{0} = -theta_{1}, which leads to the formation as in
[https://user-images.githubusercontent.com/22107547/82113976-77541180-971f-11ea-9f2f-0b045d994eb6.png](url)

#2. However, if assume theta = theta_{0} = theta_{1}, then the RHS of equation (6) from [2] becomes:
theta * L * x, which is also ok (I guess).

Thanks again for your time and effort !

**Comment by abduallahmohamed** [comment]
Can you refer to which equation you mean in [2]? 
I'm not sure I'm following theta thing

**Comment by JoeHEZHAO** [comment]
Sorry for the confusion.

First, in the paper, the reason why we use normalized adjacency matrix is from below two deductions:
![eq6](https://user-images.githubusercontent.com/14569827/82128686-f29edd00-978a-11ea-817f-8a87fef1d61e.PNG)
![eq7](https://user-images.githubusercontent.com/14569827/82128688-f3d00a00-978a-11ea-9b16-382f4911f7e3.PNG)

Notice the assumption: <a href="https://www.codecogs.com/eqnedit.php?latex=\theta&space;=&space;{\theta_{0}}'=&space;-&space;{\theta_{1}}'" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\theta&space;=&space;{\theta_{0}}'=&space;-&space;{\theta_{1}}'" title="\theta = {\theta_{0}}'= - {\theta_{1}}'" /></a>

Second, if it is possible to assume [<a href="https://www.codecogs.com/eqnedit.php?latex=\theta&space;=&space;\theta_{0}&space;=&space;\theta_{1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\theta&space;=&space;\theta_{0}&space;=&space;\theta_{1}" title="\theta = \theta_{0} = \theta_{1}" /></a>](url), then above equations will be re-formulated as:
                                                        <a href="https://www.codecogs.com/eqnedit.php?latex=g_{\theta}&space;\star&space;x&space;\approx&space;g\left&space;\mathit(L)&space;\right&space;x" target="_blank"><img src="https://latex.codecogs.com/gif.latex?g_{\theta}&space;\star&space;x&space;\approx&space;g\left&space;\mathit(L)&space;\right&space;x" title="g_{\theta} \star x \approx g\left \mathit(L) \right x" /></a>.

In this way, using normalized laplacian is plausible ?

**Comment by abduallahmohamed** [comment]
I will get back to this by the beginning of next weak, sorry for the delay

**Comment by hzzzzjzyq** [comment]
Dear Authors
Thanks for your detailed reply
can i believe the difference between stgcn and social-stgcnn as below
1.stgcn use 
𝐷̂ −1/2𝐴̂ 𝐷̂ −1/2
2.social-stgcnn use 
𝐷̂ −1/2（𝐷̂ −𝐴̂ ）𝐷̂ −1/2
lapalcian=𝐷̂ −𝐴̂       
𝐷̂ −𝐴̂  or 𝐴̂  What is the difference between the two

**Comment by hzzzzjzyq** [comment]
Dear Authors
Thanks for your detailed reply
can i believe the difference between stgcn and social-stgcnn as below
1.stgcn use
https://latex.91maths.com/s/?JTVDaGF0JTdCRCU3RCU1RSU3Qi0xJTJGMiU3RCU1Q2hhdCU3QkElN0QlN0IlNUNoYXQlN0JEJTdEJTdEJTVFJTdCLTElMkYyJTdE
2.social-stgcnn use
https://latex.91maths.com/s/?JTVDaGF0JTdCRCU3RCU1RSU3Qi0xJTJGMiU3RCglNUNoYXQlN0JEJTdELSU1Q2hhdCU3QkElN0QpJTdCJTVDaGF0JTdCRCU3RCU3RCU1RSU3Qi0xJTJGMiU3RA==
lapalcian=https://latex.91maths.com/s/?JTVDaGF0JTdCRCU3RC0lNUNoYXQlN0JBJTdE
https://latex.91maths.com/s/?JTVDaGF0JTdCRCU3RC0lNUNoYXQlN0JBJTdE or https://latex.91maths.com/s/?JTVDaGF0JTdCQSU3RA== What is the difference between the two

**Comment by hzzzzjzyq** [comment]
![Uploading image.png…]()

**Comment by hzzzzjzyq** [comment]
![2020-10-16 09-44-43屏幕截图](https://user-images.githubusercontent.com/45667990/96203466-87a13e80-0f94-11eb-8152-95aba5787e5d.png)

**Comment by hzzzzjzyq** [comment]
Dear Authors
Thanks for your detailed reply
can i believe the difference between stgcn and social-stgcnn as below
1.stgcn use
![2020-10-16 09-44-43屏幕截图](https://user-images.githubusercontent.com/45667990/96203630-f1b9e380-0f94-11eb-82aa-fb833546db97.png)

2.social-stgcnn use
![2020-10-16 09-47-52屏幕截图](https://user-images.githubusercontent.com/45667990/96203636-f7afc480-0f94-11eb-9a92-6957bea00b80.png)
lapalcian=Dhat -Ahat
![2020-10-16 09-48-18屏幕截图](https://user-images.githubusercontent.com/45667990/96203698-14e49300-0f95-11eb-8b95-c0649fbd15f9.png)
![2020-10-16 09-48-31屏幕截图](https://user-images.githubusercontent.com/45667990/96203701-1746ed00-0f95-11eb-8e8a-c2b7ccc0a663.png)
What is the difference between the two

**Comment by abduallahmohamed** [comment]
Hi, I will try to answer to my best: 
 Kipf normalization [ Not sure if this is stgcn or not] 
[[0.33333333 1.66666667 3.        ]
 [1.66666667 0.33333333 2.66666667]
 [3.         2.66666667 0.33333333]]

 Laplacian normalization [Ours] 
[[ 0.93333333 -0.34503278 -0.54772256]
 [-0.34503278  0.92857143 -0.50395263]
 [-0.54772256 -0.50395263  0.94444444]]

This how the **A**  matrix looks like after normalization, so ours row and columns sums to 0. 
I didn't try the Kipf's normalization method to see the outcome on our approach. You can test both and understand how it effects your results @hzzzzjzyq

**Comment by abduallahmohamed** [comment]
I'm not aware of a proof for this
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
