### ISSUE TITLE
ETH Annotations Frequency

### ISSUE THREAD

**Issue by os1a** [abduallahmohamed/Social-STGCNN#25]
Hi,

Thanks for your great work, I would like to ask something regrading the annotations of a dataset (e.g, ETH). 

In the file datasets/eth/test/biwi_eth.txt, the distance between frames is 10 (780, 790, ...). However, the original annotations in the eth dataset are sampled differently (780, 786, 792, ....). Am I missing something?

I downloaded the original ETH dataset from:
https://icu.ee.ethz.ch/research/datsets.html

Best,
Osama

**Comment by abduallahmohamed** [comment]
I'm really not sure about this, but this dataset configurations has been borrowed from social-stgcnn, and has been used by other related works. So, you might find more details about these files structures there.

**Comment by os1a** [comment]
Thanks for your answer,

But from where you borrowed the dataset? (social-stgcnn is your method!)

**Comment by abduallahmohamed** [comment]
Thanks for asking, my apology is this wasn't clear in the paper.  This dataset configuration is well-known, it's the same one you find in social-lstm, social-GAN and all other methods that we reported in the paper. You can check their repos directly and grab that dataloader + the dataset. The first one used it was social-LSTM, they configured it in a way called train on all leave on out. Then works afterthem kept using the same configurations for the sake of benchmarking.
