### ISSUE TITLE
How to implement on a custom video?

### ISSUE THREAD

**Issue by Mzunoven** [abduallahmohamed/Social-STGCNN#28]
Thanks for your great work.

I want to ask how to implement this network on a custom video? Can you give some instructions on how to prepare my video and do prediction?

Thanks!

**Comment by abduallahmohamed** [comment]
I originally didn't process the data as I used ETH & UCY datasets as it's. 
If I were in your place I would:
- Sample the video at fixed periods (0.2 seconds for example).
- Annotate the pedestrians in the video while having a fixed reference.
- Construct the homography matrix that converts from pixel domain to meters(real-world) domain. 
- Generate the annotation same way as eth & ucy files are.
