### ISSUE TITLE
It's unfair to compare the result with other methods!

### ISSUE THREAD

**Issue by LabMemNo003** [abduallahmohamed/Social-STGCNN#30]
https://github.com/abduallahmohamed/Social-STGCNN/issues/27
https://github.com/abduallahmohamed/Social-STGCNN/issues/14

As mentioned in above issues, the author even didn't know how the other methods calculate ADE and FDE, actually the calculations are different, but the author put all the results in one table to show the advance of Social-STGCNN.

I'm new to Human Trajectory Prediction, and I want to know the author's academic purpose.

Thanks!

**Comment by abduallahmohamed** [comment]
Hi, 
As I clarified before. 
First the FDE( which cares about the final step in the trajectory prediction, having a small number there means you didn't accumulate errors alongside your predictions)  calculations is the exact same of every other paper. As it's a straight forward equation as in our paper: 
![image](https://user-images.githubusercontent.com/22107547/91716286-f5181d80-eb54-11ea-87f7-421b9b90e118.png)
The second one is the ADE (which cares about the average error along the whole trajectory predictions), as I clarified before in both #27 and #14  the question is the comparison vs Social-GAN. GAN based methods do one prediction of the whole scene of trajectories, aka all generated trajectories are correlated with each other. In our case we don't have this, we predict the distribution of each prediction point per pedestrian, then we sample. Thus using the minimum of 20 trajectories of GAN methods which is over the scene itself is different from ours. Please do check other paper that doesn't use GAN and have their code open-sourced and you will have a clear view of how this is done. 

Nonetheless, this take the minimum of 20 predictions to quantify the accuracy of the model is not the bets way to this. Even if it's adapted through all the paper the correct way to do it is to use a metric between a point and distribution. 

Let me know if something isn't clear.
