### ISSUE TITLE
Dynamic time window

### ISSUE THREAD

**Issue by Mirorrn** [abduallahmohamed/Social-STGCNN#32]
Hello,
thanks for publishing the code.

I am interested in the use case where the number of people varies over time, in the time window considered, i.e. people can leave the scene. This changes the topology of the scene.

In the published code only trajectories with a certain length are considered and the rest is sorted out (seq_len=20). If the probable case occurs that a person leaves the scene, usually filler values can be entered for the position entries for the considered time window. I would like to know what would be the best strategy for the adjacency matrix. Should the kernel set a zero there?

**Comment by abduallahmohamed** [comment]
Thanks for asking. I didn't consider this case in the model development, but a filler can be a good option regards the type of the filler value on top of my head I would use a constant velocity model to populate the gaps as the best estimate of what it would be, even if it leaves or enters the scene. I would be interested to know how will this work for you. Thanks again.
