### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by zhyxun** [abduallahmohamed/Social-STGCNN#37]
Hi, excuse me~
How can I show the visualization result like the "social-stgcnn-pred.gif"?  Thank you.

**Comment by abduallahmohamed** [comment]
Hi, Plase check https://github.com/abduallahmohamed/Social-STGCNN/issues/9

**Comment by zhyxun** [comment]
Thank you very much for your reply!  I missed the closed issues. :) It's really helpful.
