### ISSUE TITLE
How to evaluate in different setting?

### ISSUE THREAD

**Issue by haofanwang** [abduallahmohamed/Social-STGCNN#40]
I have trained a model with obs_len=12 and pred_len=24, how can I test this model under a different setting? For example, obs_len=8 and pred_len=12.

**Comment by abduallahmohamed** [comment]
Thanks for reaching out. I think for longer predictions than what it was
trained for you might need to retrain, but for shorter predictions you can
trim [:18] the extra predicted locations before calculating the FDE/ADE
metrics while leaving the TrajectoryDataset settings the same. Yet, I still
prefer to train a new model for each variant settings as we have an edge in
terms of FDE metric.
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
