### ISSUE TITLE
Time extrapolator CNN versus LSTM decoder

### ISSUE THREAD

**Issue by arsalsyed** [abduallahmohamed/Social-STGCNN#41]
Hi, 

I was just wondering what would happen if instead of TXPCNN (for 12 steps into future) we encode graph convolutions and then feed it in LSTM to decode trajectories. something like Grip ++ (https://arxiv.org/pdf/1907.07792.pdf). your thoughts? 

Thanks
Arsal

**Comment by abduallahmohamed** [comment]
Hi Arsal, 
I'm really not sure how it will work when this swap happens, but my reasonsing to use CNN instead of LSTM/GRU is this paper: [An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence Modeling](https://arxiv.org/pdf/1803.01271.pdf) 




Thanks
