### ISSUE TITLE
Calculation of Adjacency Matrix

### ISSUE THREAD

**Issue by RyYAO98** [abduallahmohamed/Social-STGCNN#45]
Hi, thanks for your impressive work! I'm studying the implementation you released, and now there's just one issue confusing me which is related to the calculation of the adjacency matrix in [utils.py](https://github.com/abduallahmohamed/Social-STGCNN/blob/master/utils.py#L45).
As mentioned in your paper, an element of the adjacency matrix is calculated using the observed locations of two nodes:
![image](https://user-images.githubusercontent.com/37344313/111863805-93a48880-8998-11eb-9da5-524b570d0994.png)
However, in line 45 of utils.py, it's calculated using displacement (relative position) instead of absolute position:

    l2_norm = anorm(step_rel[h],step_rel[k])

Could you please explain the reason for the operation? Look forward to your reply!

**Comment by abduallahmohamed** [comment]
Hi, 

Please refer to this: https://github.com/abduallahmohamed/Social-STGCNN/issues/15 
TL:DR; the step_rel is a normalization for the trajectories. 
Please let me know if the previous issue isn't enough

Best

**Comment by RyYAO98** [comment]
> Hi,
> 
> Please refer to this: #15
> TL:DR; the step_rel is a normalization for the trajectories.
> Please let me know if the previous issue isn't enough
> 
> Best

Thanks for your answer. It's much clear now.
