### ISSUE TITLE
 the visualization of Social-STGCNN five datasets 

### ISSUE THREAD

**Issue by lyy0095** [abduallahmohamed/Social-STGCNN#49]
Hello, 
when I look into the five datasets(eth/hotel/univ/zara01/zara02) and visualization them with matplotlib,  i found they are some kind of similar, as shown below. The five datasets have obvious smilar boundarys, and horizontal movement is more than vertical movement.
![image](https://user-images.githubusercontent.com/39576105/118383991-68a38180-b635-11eb-8e3b-017eff12c054.png)

I had collected some data below to make a traj-prediction, but my dataset is extremely randomness，without such similarity like five datasets.    ( I download these scenes from Youtube and do not have Homography matrix , so my dataset are only in frame coordinates ，not in real world coordinates.)
![image (1)](https://user-images.githubusercontent.com/39576105/118384034-a7393c00-b635-11eb-829b-57aba26c653a.png)

So, Is there possible to use social-stgcnn in such randomness frame coordinates dataset with good effects?  ( training with such dataset is not good, and the traj-inference effects is bad) Or is there any methods to deal with such  randomness dataset before social-stgcnn training?

**Comment by abduallahmohamed** [comment]
I replied by email, thanks!

**Comment by chuli97** [comment]
> 您好， 当我查看五个数据集（eth/hotel/univ/zara01/zara02）并使用 matplotlib 可视化它们时，我发现它们有些相似，如下所示。五个数据集有明显的相似边界，水平移动多于垂直移动。 ![图片](https://user-images.githubusercontent.com/39576105/118383991-68a38180-b635-11eb-8e3b-017eff12c054.png)
> 
> 我在下面收集了一些数据来进行轨迹预测，但是我的数据集非常随机，没有五个数据集那样的相似性。（我从 Youtube 下载这些场景，没有 Homography 矩阵，所以我的数据集只有帧坐标，而不是真实世界坐标。） ![图片 (1)](https://user-images.githubusercontent.com/39576105/118384034-a7393c00-b635-11eb-829b-57aba26c653a.png)
> 
> 那么，是否有可能在这样的随机框架坐标数据集中使用social-stgcnn，效果很好？（用这样的数据集训练不好，traj-inference 效果不好）或者在 social-stgcnn 训练之前有什么方法可以处理这种随机性数据集？



> 您好， 当我查看五个数据集（eth/hotel/univ/zara01/zara02）并使用 matplotlib 可视化它们时，我发现它们有些相似，如下所示。五个数据集有明显的相似边界，水平移动多于垂直移动。 ![图片](https://user-images.githubusercontent.com/39576105/118383991-68a38180-b635-11eb-8e3b-017eff12c054.png)
> 
> 我在下面收集了一些数据来进行轨迹预测，但是我的数据集非常随机，没有五个数据集那样的相似性。（我从 Youtube 下载这些场景，没有 Homography 矩阵，所以我的数据集只有帧坐标，而不是真实世界坐标。） ![图片 (1)](https://user-images.githubusercontent.com/39576105/118384034-a7393c00-b635-11eb-829b-57aba26c653a.png)
> 
> 那么，是否有可能在这样的随机框架坐标数据集中使用social-stgcnn，效果很好？（用这样的数据集训练不好，traj-inference 效果不好）或者在 social-stgcnn 训练之前有什么方法可以处理这种随机性数据集？



> Hello, when I look into the five datasets(eth/hotel/univ/zara01/zara02) and visualization them with matplotlib, i found they are some kind of similar, as shown below. The five datasets have obvious smilar boundarys, and horizontal movement is more than vertical movement. ![image](https://user-images.githubusercontent.com/39576105/118383991-68a38180-b635-11eb-8e3b-017eff12c054.png)
> 
> I had collected some data below to make a traj-prediction, but my dataset is extremely randomness，without such similarity like five datasets. ( I download these scenes from Youtube and do not have Homography matrix , so my dataset are only in frame coordinates ，not in real world coordinates.) ![image (1)](https://user-images.githubusercontent.com/39576105/118384034-a7393c00-b635-11eb-829b-57aba26c653a.png)
> 
> So, Is there possible to use social-stgcnn in such randomness frame coordinates dataset with good effects? ( training with such dataset is not good, and the traj-inference effects is bad) Or is there any methods to deal with such randomness dataset before social-stgcnn training?

Hello,
I've been learning about trajectory prediction recently, and I want this project to predict the trajectory of my own video data. Can you share your visualization code with me?
If you can, please email me: liping971212@163.com ,
be deeply grateful

**Comment by abduallahmohamed** [comment]
Hi,

I'm not sure about  Social-STGCNN performance on this matter, I'd simply
train it with the dataset and see how it goes.
For visualization please check:
https://github.com/abduallahmohamed/Social-STGCNN/issues/58
------------------------------------------
Abduallah Mohamed
abduallahmohamed.com
