### ISSUE TITLE
Question about the trajectory of three degrees of freedom

### ISSUE THREAD

**Issue by hujb48** [abduallahmohamed/Social-STGCNN#52]
Hi, It is a great work. I am a new at this field, sorry to ask a little vague question:
Here is a scene  about the trajectory of three degrees of freedom, and if I want to predict the trajectory in 3D coordinates, like (xt,yt,zt) for one person. Because I want to study the trajectory not only in the walking scene, but also some competition scene like football sports or diving, so the zt information is important for me, in another words, depth information is important for me during projection transformation.
What should I do to modify the code?
Hope your can reply at your convenience,
Your, Hu! @abduallahmohamed

**Comment by abduallahmohamed** [comment]
Please check https://github.com/abduallahmohamed/Skeleton-Graph
