### ISSUE TITLE
About num_epochs? 

### ISSUE THREAD

**Issue by daeunni** [abduallahmohamed/Social-STGCNN#53]
Hello, thank you for your great work. : )

Why did you set the **epoch size to 250**? When I run it on my computer, I check that some overfitting has occurred, so I want to reduce this epoch size. I wonder if there is a problem with applying the Social STGCNN algorithm even if I reduce it.

**Comment by abduallahmohamed** [comment]
Thanks for reaching out. 
I don't think there's an issue if you reduced the epoch size to counter overfitting.

**Comment by abduallahmohamed** [comment]
I'm also wondering where did you detect overfitting?

**Comment by daeunni** [comment]
Thank you for your answer. :)

I'm currently making another model based on Social STGCNN, 
so I just wanted to know if there was **any technical problem with Social STGCNN** based on my model **when I reduced the epoch**. 

Therefore, overfitting may not be a problem of Social STGCNN.
Thanks.
