### ISSUE TITLE
PROBLEM About TCN

### ISSUE THREAD

**Issue by Ian-Shih** [abduallahmohamed/Social-STGCNN#60]
Hi, I see there are two functions ( self. tpcnns and self. tcn ) in your model. Could you tell me the difference between them? They seem just like normal Convolutions.

Both of them use Conv2D, but as is known to me, TCN uses Conv1D, doesn't it?

And, TCN has two points (Causal Convolution and Dilated Convolution), but I can't find these points in your code.

Looking forward to your reply.

**Comment by abduallahmohamed** [comment]
Our TXPCNN is a form of a TCN but built differently. It treats time as a feature channel where the conv1d TCN iirc treats time as a pixel. Nonetheless, the core concept is using CNNs to process time sequences.
