### ISSUE TITLE
could min-pedestrian greater than 1?

### ISSUE THREAD

**Issue by Lesballes** [abduallahmohamed/Social-STGCNN#61]
hello,abduallahmohamed! What you did is a very brilliant job, but i have met some problem about min-pedestrian. There are few pedestrian in my data, so i want to set min-pedestrian =1, but i met some problems. Therefore i have doubts about is it any possible  making min-pesdestrian equal 1?

**Comment by abduallahmohamed** [comment]
Hi, 

Thanks for asking. I didn't consider pedestrians =1 as this wasn't in the setup of the problem originally.
