### ISSUE TITLE
How to handle trajectories with missing frames?

### ISSUE THREAD

**Issue by Lucia-1996** [abduallahmohamed/Social-STGCNN#62]
Hi，I'm very interested to your research.I have one question.I found that obstacles with incomplete trajectories are skipped when extracting features, but the reality is that the perceived trajectories will be incomplete when pedestrians are occluded, and ignoring them may affect the accuracy of the prediction results. I'm wondering if there is a better way to handle trajectories with missing frames.
Looking forward to your reply.

**Comment by abduallahmohamed** [comment]
Hi, the dataset used in our work alongside the dataloader are borrowed from Social-GAN. This construction of the problem is a form of a standard to have a comparable results across models.

**Comment by Lucia-1996** [comment]
OK，I understand. Thanks for your quick reply.
